#!/usr/bin/env bash

set -euo pipefail

AUTORESEARCH_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
AUTORESEARCH_RUNTIME_ROOT=${AUTORESEARCH_RUNTIME_ROOT:-$AUTORESEARCH_ROOT/.runtime}

export AUTORESEARCH_ROOT
export AUTORESEARCH_RUNTIME_ROOT
export UV_PROJECT_ENVIRONMENT=${UV_PROJECT_ENVIRONMENT:-$AUTORESEARCH_ROOT/.venv}
export UV_CACHE_DIR=${UV_CACHE_DIR:-$AUTORESEARCH_ROOT/.uv-cache}
export UV_PYTHON_INSTALL_DIR=${UV_PYTHON_INSTALL_DIR:-$AUTORESEARCH_ROOT/.uv-python}
export HOME=${AUTORESEARCH_HOME:-$AUTORESEARCH_RUNTIME_ROOT/home}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export TORCHINDUCTOR_CACHE_DIR=${TORCHINDUCTOR_CACHE_DIR:-$AUTORESEARCH_RUNTIME_ROOT/torchinductor}
export TRITON_CACHE_DIR=${TRITON_CACHE_DIR:-$AUTORESEARCH_RUNTIME_ROOT/triton}

export HTTP_PROXY=${HTTP_PROXY:-http://127.0.0.1:17892}
export HTTPS_PROXY=${HTTPS_PROXY:-$HTTP_PROXY}
export http_proxy=${http_proxy:-$HTTP_PROXY}
export https_proxy=${https_proxy:-$HTTPS_PROXY}
export NO_PROXY=${NO_PROXY:-localhost,127.0.0.1,::1}
export no_proxy=${no_proxy:-$NO_PROXY}

unset ALL_PROXY all_proxy

mkdir -p \
  "$AUTORESEARCH_RUNTIME_ROOT" \
  "$HOME" \
  "$UV_CACHE_DIR" \
  "$UV_PYTHON_INSTALL_DIR" \
  "$TORCHINDUCTOR_CACHE_DIR" \
  "$TRITON_CACHE_DIR"
